apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: web
        tier: web
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - name: web-port
              containerPort: 80
