apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: k8s-rails-app
        tier: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.7.17
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: 'passw0rd'
          ports:
            - containerPort: 3360
              name: mysql-port
