kind: Service
apiVersion: v1
metadata:
  name: mysql-service
  labels:
    app: k8s-rails-app
    tier: mysql
spec:
  ports:
    - port: 3306
  selector:
    app: k8s-rails-app
    tier: mysql
  clusterIP: None
