kind: Service
apiVersion: v1
metadata:
  name: mysql
  labels:
    app: k8s-hello-world
    tier: mysql
spec:
  ports:
    - port: 3306
  selector:
    app: k8s-hello-world
    tier: mysql
  clusterIP: None
