kind: Service
apiVersion: v1
metadata:
  name: web
  labels:
    app: k8s-rails-app
spec:
  selector:
    app: k8s-rails-app
  ports:
    - port: 7000
      targetPort: nginx-port
  type: LoadBalancer
